#!/usr/bin/env bash
# loop from 1 to 10, display:
# 'bad luck' for 4th loop, 
# 'good luck' for 8th loop
# 'Best school for other iterations

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]  
	then
		echo "good luck"
	else
		echo "Best school"
	fi
	(( i++ ))
done
