#!/usr/bin/env bash
# loop from 1 to 20, display numbers 1 - 20, and:
# 4 and then 'bad luck from China' for 4th loop, 
# 9 and then 'good luck from Japan' for 9th loop
# 17 and then 'bad lock from Italy' for 17th loop

i=1

while [ $i -le 20 ]
do
	echo "$i"
	case $i in 
		4)
	echo "bad luck from China";;

		9)
	echo "good luck from Japan";;

		17)
	echo "bad luck from Italy";;
esac
	(( i++ ))
done
