#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8
cp /etc/hosts ~/hosts.new
cp /etc/hosts ~/hosts.old

#Add host name address
sed -i $'s/127.0.0.1\s*localhost//g' ~/hosts.new
echo $'127.0.0.2\tlocalhost' >> ~/hosts.new

# Add facebook address
sed -i $'/157.240.11.34\s*facebook.com//g' ~/hosts.new
echo $'8.8.8.8\t\tfacebook.com' >> ~/hosts.newcp /etc/hosts ~/hosts.old

cp -f ~/hosts.new /etc/hosts
